In [ ]:
import numpy as np

In [ ]:
# Exercise 1 : Array Creation and Manipulation
# Instructions
# Create a 1D NumPy array containing numbers from 0 to 9.

arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Exercise 2 : Type Conversion and Array Operations
# Instructions
# Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

arr=np.array([3.14, 2.17, 0, 1, 2])
intArr=arr.astype(int)
print(intArr)

[3 2 0 1 2]


In [ ]:
# Exercise 3 : Working with Multi-Dimensional Arrays
# Instructions
# Create a 3x3 NumPy array with values ranging from 1 to 9.

mat=np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
# Instructions
# Create a 2D NumPy array of shape (4, 5) filled with random numbers.

print(np.random.random(20).reshape(4,5))

[[0.58199058 0.52450616 0.8139817  0.33957067 0.59876856]
 [0.10835661 0.73899389 0.62386797 0.62332172 0.10705597]
 [0.67147448 0.56200877 0.0457881  0.018199   0.80962101]
 [0.25161409 0.82321783 0.05897333 0.50090979 0.0473796 ]]


In [ ]:
# Exercise 5 : Indexing Arrays
# Instructions
# Select the second row from a given 2D NumPy array.

array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
print(array[1])

[20 21 22 23 24]


In [ ]:
# Exercise 6 : Reversing elements
# Instructions
# Reverse the order of elements in a given 1D NumPy array (first element becomes last).

arr=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])[::-1]
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Exercise 7 : Identity Matrix
# Instructions
# Create a 4x4 identity matrix using NumPy.

idMat=np.eye(4)
print(idMat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Exercise 8 : Simple Aggregate Funcs
# Instructions
# Find the sum and average of a given 1D array.

arr=np.array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

print(arr.sum())
print(arr.mean())

45
4.5


In [ ]:
# Exercise 9 : Create Array and Change its Structure
# Instructions
# Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

mat=np.arange(1,21).reshape(4,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [ ]:
# Exercise 10 : Conditional Selection of Values
# Instructions
# Extract all odd numbers from a given NumPy array.

arr=np.array([1, 3, 5, 7, 9])
arr=arr[arr%2!=0]
print(arr)

[1 3 5 7 9]
